# Generated by Django 5.0.1 on 2024-01-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='explain_gym',
            field=models.TextField(blank=True, null=True),
        ),
    ]
