# Generated by Django 5.0.1 on 2024-01-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym_explain_gym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymtime',
            name='explain_gym_time',
        ),
        migrations.AddField(
            model_name='gymtime',
            name='explain_female_gym_time',
            field=models.TextField(blank=True, help_text='Explain what days they can come to the club', null=True, verbose_name='explain gym time'),
        ),
        migrations.AddField(
            model_name='gymtime',
            name='explain_male_gym_time',
            field=models.TextField(blank=True, help_text='Explain what days they can come to the club', null=True),
        ),
    ]
