# Generated by Django 5.0.1 on 2024-01-29 14:25

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodybuilders', '0001_initial'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('skill_name', models.CharField(max_length=50, unique=True)),
                ('description_skill', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('coaching_card', models.ImageField(upload_to='coaches/%y/%m/%d')),
                ('education_image', models.ImageField(upload_to='coaches/education/%Y/%m/%d')),
                ('alter_coaching_card', models.CharField(blank=True, max_length=50, null=True)),
                ('result_coaching_card', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('athles', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coach', to='bodybuilders.bodybuilding')),
                ('gym', models.ManyToManyField(related_name='coach', to='gyms.gym')),
                ('skil', models.ManyToManyField(related_name='coach_skills', to='coaches.skill')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coach',
                'db_table': 'coach',
            },
        ),
    ]
